### ISSUE TITLE
Use compile time DI with Play

### ISSUE THREAD

**Issue by jamespamplin** [guardian/identity-frontend#12]
https://playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection

**Comment by mchv** [comment]
Example of apps using compile time DI: https://github.com/guardian/pubflow/tree/master/app

**Comment by mchv** [comment]
Easy to follow article: http://loicdescotte.github.io/posts/play24-compile-time-di/

**Comment by jamespamplin** [comment]
Resolved by @danmassie in #32
