### ISSUE TITLE
Keyboard navigation: Some features not keyboard accessible in Firefox/Chrome

### ISSUE THREAD

**Issue by gidsg** [guardian/identity-frontend#55]
__Chrome__
# Steps to reproduce
* Open Chrome
* Opt in to profile beta
* Go to: https://profile.theguardian.com/signin
* Try to tab through sign in page

# Actual Results
* Remember Me checkbox does not receive tab focus

# Expected Results
* Remember Me is keyboard accessible

--------------
__Firefox__
# Steps to reproduce
* Open Firefox
* Opt in to profile beta
* Go to: https://profile.theguardian.com/signin
* Try to tab through sign in page

# Actual Results
* Sign in with Facebook,
Sign in with Google buttons do not get focus
* Forgotten Password does not get focus
* No visual indication that Sign In button has focus

# Expected Results
* All features are keyboard accessible, there is a visual indication of which item has focus

**Comment by jamespamplin** [comment]
Thanks for raising @gidsg, will fix soon.
